#!/hint/zsh
export DOTDIR=$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"
export XDG_STATE_HOME="$XDG_DATA_HOME/state"
export LESSHISTFILE="$XDG_CONFIG_HOME/lesshst"
export LESSOPEN='|$DOTDIR/less/lessfilter.sh %s'
export EDITOR="nvim"
export VISUAL="nvim"
export LAUNCHPAD_HOME="$XDG_CONFIG_HOME/launchpadlib"
export ZDOTDIR="$DOTDIR/zsh"
# completion func search python_envs base on this env
export CONDA_ENVS_PATH="$XDG_CONFIG_HOME/conda/envs"
export CONDARC="$DOTDIR/conda/condarc"
export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
export PYTHONUSERBASE="$XDG_DATA_HOME"
export PYTHONPATH="$PYTHONUSERBASE/lib/python$(python --version 2>&1 | awk '{print $2}' | tr -d .)/site-packages:$PYTHONPATH"
export NPM_CONFIG_USERCONFIG="$DOTDIR/node/npmrc"
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
export BOB_CONFIG="$DOTDIR/bob/config.json"
export SVN_CONFIG_DIR="$XDG_CONFIG_HOME/subversion"
export TZ="Asia/Shanghai"

## fzf相关配置
export FZF_DEFAULT_OPTS="
  --height 80% -e --ansi --reverse --border=rounded
  --color=border:#cceeff
  --walker-skip .git,node_modules,target"

## ctrl+t 用于搜索文件/路径
export FZF_CTRL_T_COMMAND='fd --follow --color=always'
# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
  --preview 'less {}' --preview-window='65%'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

## alt+c用于搜索路径并切换过去
export FZF_ALT_C_COMMAND="fd -td --follow --color=always"
# export FZF_ALT_C_OPTS="--preview 'eza --git -hl --color=always --icons {}'"
# Print tree structure in the preview window
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"

## ctrl+r用于搜索历史命令
# export FZF_CTRL_R_COMMAND="fd"
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

## 给manual加上语法高亮
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
export EZA_ICONS_AUTO=1
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
export LC_ALL=zh_CN.UTF-8
export NEOVIDE_CONFIG=$DOTDIR/neovide/config.toml
export NIRI_CONFIG=$DOTDIR/niri/config.kdl
export KITTY_CONFIG_DIRECTORY=$DOTDIR/kitty
