#!/bin/zsh
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/.local"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/.cache"
export XDG_STATE_HOME="$XDG_DATA_HOME/state"
export LESSHISTFILE="$XDG_CONFIG_HOME/.lesshst"
export EDITOR="nvim"
export VISUAL="nvim"
export LAUNCHPAD_HOME="$XDG_CONFIG_HOME/.launchpadlib"
export SSH_CONFIG_DIR="$XDG_CONFIG_HOME/.ssh"
export PYTHONUSERBASE="$XDG_DATA_HOME"
export PYTHONPATH="$PYTHONUSERBASE/lib/python$(python --version 2>&1 | awk '{print $2}' | tr -d .)/site-packages:$PYTHONPATH"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/.npmrc"
export NPM_CONFIG_USERDIR="$XDG_CONFIG_HOME/.npm"
export TMUX_CONF="$XDG_CONFIG_HOME/.tmux.conf"
export SVN_CONFIG_DIR="$XDG_CONFIG_HOME/.subversion"
## fzf相关配置
export FZF_DEFAULT_OPTS="--height 80% -e --ansi --layout=reverse --border"

## ctrl+t用于搜索文件
export FZF_CTRL_T_COMMAND='fd -t f --follow -H --exclude .git --color=always'
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"

## alt+c用于寻找路径（文件夹）
export FZF_ALT_C_COMMAND="fd -t d --follow -H --color=always"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

## ctrl+r用于搜索历史命令
export FZF_CTRL_R_OPTS="--height 50%"

## 给manual加上语法高亮
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
# export MANROFFOPT="-c"
if ! echo "$PATH" | grep -q '/snap/bin'; then
    export PATH="$PATH:/snap/bin"
fi
export PATH="/opt/cmake-3.29.0-rc3-linux-x86_64/bin:$XDG_DATA_HOME/bin:/opt/nvim-linux64/bin:$PATH"
DOTDIR='/home/witty/.config/Dotfiles'
