-- Doskey aliases for Clink (cmd.exe).

os.setalias("ls", "eza --icons=auto $*")
os.setalias("la", "eza --icons=auto -a $*")
os.setalias("ll", "eza --icons=auto -l $*")
os.setalias("lla", "eza --icons=auto -al $*")
os.setalias("v", "nvim $*")
os.setalias("lg", "lazygit $*")
os.setalias("gs", "git status $*")
os.setalias("gss", "git status --short $*")
os.setalias("grs", "git remote show $*")
os.setalias("gsw", "git switch $*")
os.setalias("gswc", "git switch --create $*")
os.setalias("gb", "git branch $*")
os.setalias("gbd", "git branch --delete $*")
os.setalias("gbD", "git branch --delete --force $*")
os.setalias("gbvv", "git branch -vv $*")
os.setalias("grv", "git remote -v $*")
os.setalias("gpl", "git pull $*")
os.setalias("ga", "git add $*")
os.setalias("gco", "git checkout $*")
os.setalias("gpo", "git push origin $*")
os.setalias("glog", "git log --decorate --graph --oneline $*")
os.setalias("spr", "proxy_on $*")
os.setalias("gpr", "proxy_status $*")
os.setalias("cpr", "proxy_off $*")
os.setalias("elt", "enable-linux-tools")
os.setalias("dlt", "disable-linux-tools")
os.setalias("zb", "z -b $*")
os.setalias("zf", "z -I $*")
os.setalias("zi", "z -i $*")
os.setalias("zl", "z -l $*")
os.setalias("zt", "z -t $*")
os.setalias("zr", "z -r $*")
os.setalias("zc", "z -c $*")
os.setalias("ze", "z -e $*")
os.setalias("zx", "z -x $*")
os.setalias("zbi", "z -b -I $*")
