os.setalias("ls", "eza --icons=auto $*")
os.setalias("ll", "eza --icons=auto -l $*")
os.setalias("v", "nvim $*")
os.setalias("lg", "lazygit $*")
os.setalias("gs", "git status $*")
os.setalias("gss", "git status --short $*")
os.setalias("grs", "git remote show $*")
os.setalias("gsw", "git switch $*")
os.setalias("gswc", "git switch --create $*")
os.setalias("gb", "git branch $*")
os.setalias("gbd", "git branch --delete $*")
os.setalias("gbD", "git branch --delete --force $*")
os.setalias("gbvv", "git branch -vv $*")
os.setalias("grv", "git remote -v $*")
os.setalias("gpl", "git pull $*")
os.setalias("ga", "git add $*")
os.setalias("gco", "git checkout $*")
os.setalias("gpo", "git push origin $*")
os.setalias("glog", "git log --decorate --graph --oneline $*")
